# BSE_StockData_Analyst_By_Numpy

In [1]:
import numpy as np


In [2]:
dataset = np.genfromtxt('AgriExport_BSE_StockData.csv', delimiter=',', skip_header=1, usecols=(1, 2, 3, 4, 5))


In [3]:
dataset.shape

(30, 5)

In [12]:
close_prices = dataset[:,3]

In [13]:
close_prices[:5]

array([168.19, 197.93, 184.21, 182.84, 161.97])

In [14]:
average_prices=np.mean(close_prices)

In [15]:
average_prices

np.float64(171.959)

In [16]:
highest_prices=np.max(close_prices)

In [17]:
highest_prices

np.float64(200.38)

In [18]:
volumes=dataset[:,4]

In [20]:
volumes[:5]

array([36105., 20230., 25707., 31976., 33776.])

In [21]:
highest_volume_condition=volumes>40000

In [22]:
heavy_trading_day_prices = close_prices[highest_volume_condition]

In [23]:
heavy_trading_day_prices

array([158.97, 158.71, 157.87, 171.36, 156.3 , 173.29])

In [24]:
high_prices= dataset[:,1]

In [25]:
low_prices= dataset[:,2]

In [33]:
daily_fluctuation=[high_prices-low_prices]

In [35]:
daily_fluctuation[:5]

[array([10.96,  5.98, 10.05, 13.75, 13.22, 14.16,  6.01, 10.1 ,  8.83,
        14.85, 10.05,  8.24,  2.36, 17.52, 10.69, 14.52, 11.75,  7.35,
        10.15,  4.71, 18.5 , 14.58, 13.43, 10.62, 10.18, 13.23,  9.36,
         9.51, 10.39,  9.18])]